name: Rust

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:

  formatting:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - uses: actions-rs/toolchain@v1
      with:
        profile: minimal
        toolchain: stable
        target: thumbv7em-none-eabihf
        override: true
        components: rustfmt

    - name: Check formatting
      run: cargo fmt --all -- --check

  build-nostd:
    runs-on: ubuntu-latest

    needs:
    - formatting

    steps:
    - uses: actions/checkout@v2

    - uses: actions-rs/toolchain@v1
      with:
        profile: minimal
        toolchain: nightly
        target: thumbv7em-none-eabihf
        override: true

    - name: Build no_std
      run: cargo build --verbose --target thumbv7em-none-eabihf -Z avoid-dev-deps

  build:
    runs-on: ubuntu-latest

    needs:
    - formatting

    strategy:
      matrix:
        include:
          - name: stable
            rust: stable

          - name: beta
            rust: beta

          - name: nightly
            rust: nightly

          - name: msrv
            rust: 1.41.0

    steps:
    - uses: actions/checkout@v2

    - uses: actions-rs/toolchain@v1
      with:
        profile: minimal
        toolchain: ${{ matrix.rust }}
        override: true
        components: rustfmt

    - name: Install dependencies
      run: |
        sudo add-apt-repository -y "deb http://archive.ubuntu.com/ubuntu `lsb_release -sc` main universe restricted multiverse"
        sudo apt-get update -y -qq
        sudo apt-get install libsdl2-dev imagemagick

    - name: Build
      run: cargo build --verbose

    - name: Run tests
      run: |
        cargo test --verbose
        cargo test --verbose --no-default-features

    - name: Build examples
      run: cargo build --examples --verbose

    - name: Check example images
      run: |
        mkdir -p ./target/screenshots
        EG_SIMULATOR_DUMP="./target/screenshots/left.png" cargo run --example left
        compare -metric AE ./assets/left.png ./target/screenshots/left.png result.png
        EG_SIMULATOR_DUMP="./target/screenshots/right.png" cargo run --example right
        compare -metric AE ./assets/right.png ./target/screenshots/right.png result.png
        EG_SIMULATOR_DUMP="./target/screenshots/center.png" cargo run --example center
        compare -metric AE ./assets/center.png ./target/screenshots/center.png result.png
        EG_SIMULATOR_DUMP="./target/screenshots/justified.png" cargo run --example justified
        compare -metric AE ./assets/justified.png ./target/screenshots/justified.png result.png
        EG_SIMULATOR_DUMP="./target/screenshots/specials.png" cargo run --example specials
        compare -metric AE ./assets/specials.png ./target/screenshots/specials.png result.png
        EG_SIMULATOR_DUMP="./target/screenshots/vertical.png" cargo run --example vertical
        compare -metric AE ./assets/vertical.png ./target/screenshots/vertical.png result.png
        EG_SIMULATOR_DUMP="./target/screenshots/colored_text.png" cargo run --example colored_text
        compare -metric AE ./assets/colored_text.png ./target/screenshots/colored_text.png result.png
        EG_SIMULATOR_DUMP="./target/screenshots/extra_styles.png" cargo run --example extra_styles
        compare -metric AE ./assets/extra_styles.png ./target/screenshots/extra_styles.png result.png

  docs:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - uses: actions-rs/toolchain@v1
      with:
        profile: minimal
        toolchain: stable
        target: thumbv7em-none-eabihf
        override: true
    
    - name: Check doc links
      run: |
        cargo install cargo-deadlinks
        cargo deadlinks --ignore-fragments
